---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: opendesk-service-account
  namespace: opendesk
  labels:
    app: opendesk
    component: service-account
    platform: opendesk
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: opendesk-service-role
  namespace: opendesk
rules:
  - apiGroups: [""]
    resources: ["secrets", "configmaps"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: opendesk-service-role-binding
  namespace: opendesk
subjects:
  - kind: ServiceAccount
    name: opendesk-service-account
    namespace: opendesk
roleRef:
  kind: Role
  name: opendesk-service-role
  apiGroup: rbac.authorization.k8s.io
