# SPDX-License-Identifier: Apache-2.0
# Attic binary cache server integration test
#
# Tests that the Attic binary cache server (modules/attic-server.nix)
# starts and serves its HTTP API.

{ pkgs, ... }:

{
  name = "attic-server";

  nodes = {
    attic =
      { ... }:
      {
        imports = [ ../modules/attic-server.nix ];

        services.attic = {
          enable = true;
          listenPort = 8080;
          openFirewall = false;
          cacheDir = "/var/lib/attic";
        };

        environment.systemPackages = [ pkgs.attic ];
      };

    client =
      { ... }:
      {
        nix.settings = {
          substituters = [ "http://attic:8080" ];
          trusted-public-keys = [ "attic.internal-1:abc123" ];
        };
      };
  };

  testScript = ''
    start_all()

    # Start Attic server
    attic.wait_for_unit("attic.service")
    attic.wait_for_open_port(8080)

    # Verify the HTTP API responds
    attic.succeed("curl -fsS http://localhost:8080/ >/dev/null")

    # Verify the signing key was generated by the module
    attic.succeed("test -f /etc/attic/signing.key")

    # Verify the cache directory exists with correct ownership
    attic.succeed("test -d /var/lib/attic/cache")
    attic.succeed("stat -c '%U' /var/lib/attic | grep -q attic")

    # Client node is configured to use the cache
    client.succeed("grep -q 'http://attic:8080' /etc/nix/nix.conf || test -f /etc/nix/nix.conf")
  '';
}
