---
apiVersion: v1
kind: Secret
metadata:
  name: opencode-registry-pull-secret
  namespace: opendesk
  labels:
    app: opendesk
    component: image-pull-secret
    registry: opencode.de
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: "{\"auths\":{\"registry.opencode.de\":{\"username\":\"weiss\",\"password\":\"glpat-RWF58M7NPeyay0BDeHSNGG86MQp1Ojd6Ygk.01.0z17kdnvg\"}}}"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: opendesk-service-account
  namespace: opendesk
  labels:
    app: opendesk
    component: service-account
imagePullSecrets:
  - name: opencode-registry-pull-secret
---