---
apiVersion: v1
kind: Secret
metadata:
  name: opencode-registry-pull-secret
  namespace: opendesk
  labels:
    app: opendesk
    component: image-pull-secret
    registry: opencode.de
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5vcGVuY29kZS5kZSI6eyJ1c2VybmFtZSI6InRvYmlhcy53ZWlzcyIsInBhc3N3b3JkIjoiZ2xwYXQtX0pWRjFvc2lhNTBiS09PSnhuYXNLMjg2TVFwMU9qZDZZZ2suMDEuMHowZ3dxYmRkIiwiZW1haWwiOiIiLCJhdXRoIjoiZEc5aWFXRnpMbmRsYVhOek9tZHNjR0YwTFY5S1ZrWXhiM05wWVRVd1lrdFBUMHA0Ym1GelN6STROazFSY0RGUGFtUTJXV2RyTGpBeExqQjZNR2QzY1dKa1pBPT0ifX19
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: opendesk-service-account
  namespace: opendesk
  labels:
    app: opendesk
    component: service-account
imagePullSecrets:
  - name: opencode-registry-pull-secret
---