---
apiVersion: v1
kind: Secret
metadata:
  name: opencode-registry-pull-secret
  namespace: opendesk
  labels:
    app: opendesk
    component: image-pull-secret
    registry: opencode.de
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5vcGVuY29kZS5kZSI6eyJ1c2VybmFtZSI6IndlaXNzIiwicGFzc3dvcmQiOiJnbHBhdC1SV0ZxWTJOUGV5YXkwQkRlSFNOR1c4Nk1RcDFPamp6WTIifX19
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: opendesk-service-account
  namespace: opendesk
  labels:
    app: opendesk
    component: service-account
imagePullSecrets:
  - name: opencode-registry-pull-secret
---